<?xml version="1.0" encoding="UTF-8"?>
<robot generator="Robot 7.1 (Python 3.12.4 on win32)" generated="2024-10-17T11:31:18.505782" rpa="false" schemaversion="5">
<suite id="s1" name="Login" source="C:\QAprj\prjs\stdAppiumMarkX\tests\login.robot">
<test id="s1-t1" name="Should Login with success" line="10">
<kw name="Start Session" owner="base" type="SETUP">
<kw name="Open Application" owner="AppiumLibrary">
<msg time="2024-10-17T11:31:26.499057" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002064044BBF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2024-10-17T11:31:31.092211" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002063F768E90&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2024-10-17T11:31:35.497204" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000020640478A70&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-10-17T11:31:40.271972" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-10-17T11:31:40.270973" elapsed="0.020562">No application is open</status>
</kw>
<msg time="2024-10-17T11:31:40.294555" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-10-17T11:31:40.357571" level="FAIL">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000020640479430&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</msg>
<arg>http://localhost:4723</arg>
<arg>platformName=Android</arg>
<arg>deviceName=Android Emulator</arg>
<arg>automationName=UIAutomator2</arg>
<arg>app=${EXECDIR}/apps/markx.apk</arg>
<arg>udid=emulator-5554</arg>
<arg>autoGrantPermissions=true</arg>
<doc>Opens a new application to given Appium server.
Capabilities of appium server, Android and iOS,
Please check https://appium.io/docs/en/2.1/cli/args/
| *Option*            | *Man.* | *Description*     |
| remote_url          | Yes    | Appium server url |
| alias               | no     | alias             |
| strict_ssl          | No     | allows you to send commands to an invalid certificate host like a self-signed one. |</doc>
<status status="FAIL" start="2024-10-17T11:31:20.839237" elapsed="19.525406">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000020640479430&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="Wait Until Page Contains" owner="AppiumLibrary">
<arg>Endereço IP da Api</arg>
<arg>10</arg>
<doc>Waits until `text` appears on current page.</doc>
<status status="NOT RUN" start="2024-10-17T11:31:40.364643" elapsed="0.000000"/>
</kw>
<status status="FAIL" start="2024-10-17T11:31:20.838239" elapsed="19.526404">MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000020640479430&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))</status>
</kw>
<kw name="Finish Session" owner="base" type="TEARDOWN">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-10-17T11:31:40.488441" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-10-17T11:31:40.488441" elapsed="0.005621">No application is open</status>
</kw>
<msg time="2024-10-17T11:31:40.500065" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-10-17T11:31:40.515667" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-10-17T11:31:40.487445" elapsed="0.029220">No application is open</status>
</kw>
<kw name="Close Application" owner="AppiumLibrary">
<kw name="Capture Page Screenshot" owner="AppiumLibrary">
<msg time="2024-10-17T11:31:40.518183" level="FAIL">No application is open</msg>
<doc>Takes a screenshot of the current page and embeds it into the log.</doc>
<status status="FAIL" start="2024-10-17T11:31:40.516665" elapsed="0.002529">No application is open</status>
</kw>
<msg time="2024-10-17T11:31:40.522179" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-10-17T11:31:40.526214" level="FAIL">No application is open</msg>
<doc>Closes the current application and also close webdriver session.</doc>
<status status="FAIL" start="2024-10-17T11:31:40.516665" elapsed="0.010571">No application is open</status>
</kw>
<status status="FAIL" start="2024-10-17T11:31:40.487445" elapsed="0.039791">Several failures occurred:

1) No application is open

2) No application is open</status>
</kw>
<status status="FAIL" start="2024-10-17T11:31:20.836245" elapsed="19.691989">Setup failed:
MaxRetryError: HTTPConnectionPool(host='localhost', port=4723): Max retries exceeded with url: /session (Caused by NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000020640479430&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente'))

Also teardown failed:
Several failures occurred:

1) No application is open

2) No application is open</status>
</test>
<doc>logs/</doc>
<status status="FAIL" start="2024-10-17T11:31:18.511024" elapsed="22.040885"/>
</suite>
<statistics>
<total>
<stat pass="0" fail="1" skip="0">All Tests</stat>
</total>
<tag>
</tag>
<suite>
<stat pass="0" fail="1" skip="0" id="s1" name="Login">Login</stat>
</suite>
</statistics>
<errors>
<msg time="2024-10-17T11:31:26.499057" level="WARN">Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002064044BBF0&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2024-10-17T11:31:31.092211" level="WARN">Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x000002063F768E90&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2024-10-17T11:31:35.497204" level="WARN">Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('&lt;urllib3.connection.HTTPConnection object at 0x0000020640478A70&gt;: Failed to establish a new connection: [WinError 10061] Nenhuma conexão pôde ser feita porque a máquina de destino as recusou ativamente')': /session</msg>
<msg time="2024-10-17T11:31:40.294555" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-10-17T11:31:40.500065" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
<msg time="2024-10-17T11:31:40.522179" level="WARN">Keyword 'Capture Page Screenshot' could not be run on failure: No application is open</msg>
</errors>
</robot>
